services:
  nginx:
    image: nginx:latest
    configs:
      - source: vote-conf
        target: /etc/nginx/conf.d/vote.conf
        
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  worker:
    build:
      context: https://github.com/UffizziCloud/example-voting-worker
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    build:
      context: https://github.com/UffizziCloud/example-voting-vote
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M

  result:
    build:
      context: https://github.com/UffizziCloud/example-voting-result
      dockerfile: Dockerfile
    environment:
      PORT: 8088

configs: 
  vote-conf:
    file:  ./vote.conf
    
continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  share_to_github: true
  delete_preview_after: 1h

ingress:
  service: nginx
  port: 8080
